"""Install and verify the stable command agent clients use to start Valkama.

The launcher is service-owned user state. Client configuration names the stable
launcher path; only its managed shim records where the current checkout lives.
Moving the checkout therefore requires one explicit reinstall, not edits in
every client and project configuration.
"""

from __future__ import annotations

import base64
import contextlib
import hashlib
import importlib
import json
import ntpath
import os
import shlex
import stat
import subprocess
import sys
import tempfile
from collections.abc import Iterator
from pathlib import Path

from . import processes

SCHEMA_VERSION = 1
MANIFEST_NAME = "valkama-launcher.json"
SHIM_NAME = "valkama-launcher.py"

_PROCESS_TERMINATE = 0x0001
_SYNCHRONIZE = 0x00100000
_PROCESS_QUERY_LIMITED_INFORMATION = 0x1000

_WINDOWS_LISTENER_QUERY = r"""& {
param([int]$Port)
$ErrorActionPreference = "Stop"
$connections = @(
    Get-NetTCPConnection -State Listen -ErrorAction Stop |
        Where-Object { $_.LocalPort -eq $Port }
)
$owners = @()
foreach ($processId in @($connections | Select-Object -ExpandProperty OwningProcess -Unique)) {
    $process = Get-CimInstance Win32_Process -Filter "ProcessId = $processId" -ErrorAction SilentlyContinue
    $commandLine = if ($null -eq $process) { "" } else { [string]$process.CommandLine }
    $executablePath = if ($null -eq $process) { "" } else { [string]$process.ExecutablePath }
    $identityToken = if ($null -eq $process) {
        ""
    } else {
        $process.CreationDate.ToUniversalTime().ToString("o", [Globalization.CultureInfo]::InvariantCulture)
    }
    $encodedCommand = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($commandLine))
    $encodedExecutable = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($executablePath))
    $owners += [pscustomobject]@{
        pid = [int]$processId
        command_line_utf8 = $encodedCommand
        executable_path_utf8 = $encodedExecutable
        identity_token = $identityToken
    }
}
ConvertTo-Json -InputObject @($owners) -Compress
}"""


class LauncherError(RuntimeError):
    """The launcher cannot be changed without risking an unmanaged file."""


def source_script() -> Path:
    return (Path(__file__).resolve().parents[1] / "valkama.py").resolve()


def default_directory(platform_name: str | None = None) -> Path:
    platform = platform_name or os.name
    if platform == "nt":
        local = os.environ.get("LOCALAPPDATA")
        if not local:
            raise LauncherError("LOCALAPPDATA is required to install the Windows launcher")
        return (Path(local) / "Valkama" / "bin").resolve()
    configured = os.environ.get("XDG_BIN_HOME")
    target = Path(configured).expanduser() if configured else Path.home() / ".local" / "bin"
    return target.resolve()


def command_name(platform_name: str | None = None) -> str:
    return "valkama.cmd" if (platform_name or os.name) == "nt" else "valkama"


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _paths(directory: Path, platform_name: str) -> dict[str, Path]:
    return {
        "command": directory / command_name(platform_name),
        "shim": directory / SHIM_NAME,
        "manifest": directory / MANIFEST_NAME,
    }


def _shim_bytes(script: Path) -> bytes:
    encoded = json.dumps(str(script), ensure_ascii=False)
    text = (
        '"""Generated by `valkama.py launcher install`; do not edit."""\n\n'
        "from __future__ import annotations\n\n"
        "import runpy\n"
        "import sys\n"
        "from pathlib import Path\n\n"
        f"SOURCE = Path({encoded})\n"
        "if not SOURCE.is_file():\n"
        '    raise SystemExit(f"Valkama source entry point is missing: {SOURCE}")\n'
        "sys.path.insert(0, str(SOURCE.parent))\n"
        'runpy.run_path(str(SOURCE), run_name="__main__")\n'
    )
    return text.encode("utf-8")


def _command_bytes(platform_name: str, python: Path) -> tuple[bytes, int]:
    if platform_name == "nt":
        interpreter = subprocess.list2cmdline([str(python)])
        text = f'@echo off\r\n{interpreter} "%~dp0{SHIM_NAME}" %*\r\n'
        return text.encode("utf-8"), stat.S_IREAD | stat.S_IWRITE
    interpreter = shlex.quote(str(python))
    text = (
        '#!/bin/sh\nSCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\n'
        f'exec {interpreter} "$SCRIPT_DIR/{SHIM_NAME}" "$@"\n'
    )
    return text.encode("utf-8"), 0o755


def _atomic_write(path: Path, data: bytes, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(handle, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def _read_manifest(path: Path) -> tuple[dict[str, object] | None, str | None]:
    if not path.is_file():
        return None, None
    try:
        document = json.loads(path.read_text(encoding="utf-8", errors="strict"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
        return None, str(error)
    if not isinstance(document, dict):
        return None, "manifest must be a JSON object"
    return document, None


def _file_problem(path: Path, expected: object) -> str | None:
    if not isinstance(expected, str):
        return f"manifest does not own {path.name}"
    if not path.is_file():
        return f"managed file is missing: {path.name}"
    try:
        digest = _sha256(path.read_bytes())
    except OSError as error:
        return f"managed file is unreadable: {path.name}: {error}"
    if digest != expected:
        return f"managed file was modified: {path.name}"
    return None


def status(
    directory: str | os.PathLike[str] | None = None,
    *,
    platform_name: str | None = None,
) -> dict[str, object]:
    platform = platform_name or os.name
    root = Path(directory).expanduser().resolve() if directory else default_directory(platform)
    paths = _paths(root, platform)
    present = {name: path.is_file() for name, path in paths.items()}
    base = {
        "schema_version": SCHEMA_VERSION,
        "directory": str(root),
        "command": str(paths["command"]),
        "shim": str(paths["shim"]),
        "manifest": str(paths["manifest"]),
        "args": ["mcp"],
    }
    if not any(present.values()):
        return {**base, "state": "missing"}

    manifest, error = _read_manifest(paths["manifest"])
    if manifest is None:
        state = "unmanaged" if error is None else "drifted"
        return {**base, "state": state, "detail": error or "managed manifest is missing"}
    if manifest.get("schema_version") != SCHEMA_VERSION:
        return {**base, "state": "drifted", "detail": "unsupported launcher manifest schema"}
    if manifest.get("platform") != platform:
        return {**base, "state": "drifted", "detail": "launcher platform does not match"}
    files = manifest.get("files")
    if not isinstance(files, dict):
        return {**base, "state": "drifted", "detail": "launcher manifest has no file hashes"}

    problems = [
        problem
        for name in ("command", "shim")
        if (problem := _file_problem(paths[name], files.get(paths[name].name))) is not None
    ]
    source_value = manifest.get("source_script")
    source = Path(source_value) if isinstance(source_value, str) else None
    source_available = source is not None and source.is_file()
    if source is None:
        problems.append("manifest has no source_script")
        source_detail = None
    elif not source_available:
        source_detail = f"source entry point is missing: {source}"
    else:
        source_detail = None

    return {
        **base,
        "state": "installed" if not problems else "drifted",
        "source_script": str(source) if source is not None else None,
        "source_available": source_available,
        "python": manifest.get("python"),
        "detail": "; ".join([*problems, *([source_detail] if source_detail else [])]) or None,
    }


def _managed_status(
    directory: str | os.PathLike[str] | None,
    platform_name: str,
) -> dict[str, object]:
    current = status(directory, platform_name=platform_name)
    if current["state"] != "installed":
        detail = current.get("detail") or "the launcher is not installed"
        raise LauncherError(f"managed launcher ownership is unavailable: {detail}")
    return current


def _windows_listener_processes(port: int, *, runner=None) -> list[dict[str, object]]:
    run = runner or processes.run_text
    result = run(
        [
            "powershell.exe",
            "-NoLogo",
            "-NoProfile",
            "-NonInteractive",
            "-Command",
            _WINDOWS_LISTENER_QUERY,
            str(port),
        ]
    )
    if result.returncode != 0:
        raise LauncherError(f"could not inspect the process listening on port {port}")
    try:
        document = json.loads(result.stdout or "[]")
    except json.JSONDecodeError as error:
        raise LauncherError("Windows returned malformed listener ownership data") from error
    rows = document if isinstance(document, list) else [document]
    owners: list[dict[str, object]] = []
    for row in rows:
        pid = row.get("pid") if isinstance(row, dict) else None
        if (
            not isinstance(row, dict)
            or not isinstance(pid, int)
            or isinstance(pid, bool)
            or pid <= 0
        ):
            raise LauncherError("Windows returned malformed listener ownership data")
        encoded_command = row.get("command_line_utf8")
        encoded_executable = row.get("executable_path_utf8")
        identity_token = row.get("identity_token")
        if (
            not isinstance(encoded_command, str)
            or not isinstance(encoded_executable, str)
            or not isinstance(identity_token, str)
        ):
            raise LauncherError("Windows returned malformed listener ownership data")
        try:
            command_line = base64.b64decode(encoded_command, validate=True).decode(
                "utf-8", errors="strict"
            )
            executable_path = base64.b64decode(encoded_executable, validate=True).decode(
                "utf-8", errors="strict"
            )
        except (UnicodeDecodeError, ValueError) as error:
            raise LauncherError("Windows returned malformed listener ownership data") from error
        owners.append(
            {
                "pid": pid,
                "command_line": command_line,
                "executable_path": executable_path,
                "identity_token": identity_token,
            }
        )
    return owners


def _normalized_windows_path(value: str | os.PathLike[str]) -> str:
    """Normalize with Windows' non-expanding case semantics."""

    return ntpath.normcase(ntpath.normpath(os.fspath(value)))


def _same_windows_path(
    left: str | os.PathLike[str],
    right: str | os.PathLike[str],
) -> bool:
    return bool(left and right) and _normalized_windows_path(left) == _normalized_windows_path(
        right
    )


def _command_line_names_shim(command_line: str, shim: str | os.PathLike[str]) -> bool:
    """Whether the managed shim is the script argument of one Python process."""

    try:
        arguments = shlex.split(command_line, posix=False)
    except ValueError:
        return False
    if len(arguments) < 2:
        return False
    script = arguments[1]
    if len(script) >= 2 and script.startswith('"') and script.endswith('"'):
        script = script[1:-1]
    return _same_windows_path(script, shim)


def _classify_listener_processes(
    port: int,
    python: str | os.PathLike[str],
    shim: str | os.PathLike[str],
    owners: list[dict[str, object]],
) -> dict[str, object]:
    unique: dict[int, dict[str, object]] = {}
    uncertain = False
    for owner in owners:
        pid = owner.get("pid")
        command_line = owner.get("command_line")
        executable_path = owner.get("executable_path")
        identity_token = owner.get("identity_token")
        if (
            isinstance(pid, int)
            and not isinstance(pid, bool)
            and pid > 0
            and isinstance(command_line, str)
            and bool(command_line)
            and isinstance(executable_path, str)
            and bool(executable_path)
            and isinstance(identity_token, str)
            and bool(identity_token)
        ):
            normalized = {
                "pid": pid,
                "command_line": command_line,
                "executable_path": executable_path,
                "identity_token": identity_token,
            }
            if pid in unique and unique[pid] != normalized:
                uncertain = True
            unique[pid] = normalized
        else:
            uncertain = True
    if uncertain:
        return {
            "state": "foreign",
            "port": port,
            "pid": None,
            "detail": (
                f"port {port} has listener ownership Windows could not verify; "
                "Valkama left it untouched. Stop that process or choose another port, "
                "then try again."
            ),
        }
    if not unique:
        return {
            "state": "free",
            "port": port,
            "pid": None,
            "executable_path": None,
            "process_identity": None,
            "detail": None,
        }
    managed = [
        pid
        for pid, owner in unique.items()
        if _same_windows_path(str(owner["executable_path"]), python)
        and _command_line_names_shim(str(owner["command_line"]), shim)
    ]
    if len(unique) == 1 and len(managed) == 1:
        pid = managed[0]
        owner = unique[pid]
        return {
            "state": "managed",
            "port": port,
            "pid": pid,
            "executable_path": owner["executable_path"],
            "process_identity": owner["identity_token"],
            "detail": f"port {port} is owned by managed launcher process {pid}",
        }
    listed = ", ".join(str(pid) for pid in sorted(unique))
    return {
        "state": "foreign",
        "port": port,
        "pid": next(iter(unique)) if len(unique) == 1 else None,
        "detail": (
            f"port {port} is held by process {listed} that was not started by the managed "
            "Valkama launcher; Valkama left it untouched. Stop that process or choose "
            "another port, then try again."
        ),
    }


def listener_status(
    directory: str | os.PathLike[str] | None = None,
    *,
    port: int = 8642,
    platform_name: str | None = None,
    process_reader=None,
) -> dict[str, object]:
    """Classify a listener from its process identity, never its HTTP payload."""

    if not 1 <= port <= 65535:
        raise LauncherError(f"invalid listener port {port}")
    platform = platform_name or os.name
    if platform != "nt" and process_reader is None:
        raise LauncherError("managed listener inspection is currently available only on Windows")
    current = _managed_status(directory, platform)
    python = current.get("python")
    if not isinstance(python, str) or not ntpath.isabs(python):
        raise LauncherError("managed launcher manifest has no absolute Python identity")
    read = process_reader or _windows_listener_processes
    owners = read(port)
    return _classify_listener_processes(port, python, str(current["shim"]), owners)


@contextlib.contextmanager
def _windows_process_handle(pid: int) -> Iterator[int]:
    """Hold the Windows process object so its PID cannot be substituted."""

    winapi = importlib.import_module("_winapi")
    access = _PROCESS_TERMINATE | _SYNCHRONIZE | _PROCESS_QUERY_LIMITED_INFORMATION
    try:
        handle = winapi.OpenProcess(access, False, pid)
    except OSError as error:
        if getattr(error, "winerror", None) in {87, 1168}:
            raise ProcessLookupError(pid) from error
        raise
    try:
        yield handle
    finally:
        winapi.CloseHandle(handle)


def _terminate_windows_process_handle(handle: int) -> None:
    winapi = importlib.import_module("_winapi")
    winapi.TerminateProcess(handle, 1)


def _same_listener_process(first: dict[str, object], second: dict[str, object]) -> bool:
    first_executable = first.get("executable_path")
    second_executable = second.get("executable_path")
    return bool(
        isinstance(first.get("pid"), int)
        and first["pid"] == second.get("pid")
        and isinstance(first_executable, str)
        and isinstance(second_executable, str)
        and _same_windows_path(first_executable, second_executable)
        and isinstance(first.get("process_identity"), str)
        and first["process_identity"] == second.get("process_identity")
    )


def _refused_stop(port: int, detail: str, *, pid: object = None) -> dict[str, object]:
    message = detail.strip()
    if "left it untouched" not in message.lower():
        message = f"{message} Valkama left it untouched."
    return {
        "state": "refused",
        "port": port,
        "pid": pid if isinstance(pid, int) and not isinstance(pid, bool) else None,
        "detail": message,
    }


def stop_listener(
    directory: str | os.PathLike[str] | None = None,
    *,
    port: int = 8642,
    platform_name: str | None = None,
    process_reader=None,
    process_guard=None,
    stopper=None,
) -> dict[str, object]:
    """Stop one listener only while holding and re-verifying its process object."""

    if not 1 <= port <= 65535:
        raise LauncherError(f"invalid listener port {port}")
    try:
        current = listener_status(
            directory,
            port=port,
            platform_name=platform_name,
            process_reader=process_reader,
        )
    except LauncherError as error:
        return _refused_stop(port, str(error))
    if current["state"] == "free":
        return {**current, "detail": f"port {port} is already free"}
    if current["state"] != "managed":
        return {**current, "state": "refused"}
    pid = current["pid"]
    if not isinstance(pid, int):
        return _refused_stop(port, "managed listener status had no process id")
    manager = (
        process_guard(pid)
        if process_guard is not None
        else _windows_process_handle(pid)
        if stopper is None
        else contextlib.nullcontext(pid)
    )
    try:
        with manager as handle:
            try:
                confirmed = listener_status(
                    directory,
                    port=port,
                    platform_name=platform_name,
                    process_reader=process_reader,
                )
            except LauncherError as error:
                return _refused_stop(port, f"listener identity could not be re-verified: {error}")
            if confirmed["state"] == "free":
                return {
                    **confirmed,
                    "detail": "listener exited before it could be stopped",
                }
            if confirmed["state"] != "managed":
                return _refused_stop(
                    port,
                    str(confirmed.get("detail") or "listener ownership changed before stop"),
                    pid=confirmed.get("pid"),
                )
            if not _same_listener_process(current, confirmed):
                return _refused_stop(
                    port,
                    "listener process identity changed before stop",
                    pid=confirmed.get("pid"),
                )
            terminate = stopper or _terminate_windows_process_handle
            terminate(handle)
    except ProcessLookupError:
        return {"state": "free", "port": port, "pid": None, "detail": "listener exited"}
    except OSError as error:
        return _refused_stop(port, f"could not safely stop managed listener process {pid}: {error}")
    return {
        "state": "stopped",
        "port": port,
        "pid": pid,
        "detail": f"stopped managed launcher process {pid}",
    }


def install(
    directory: str | os.PathLike[str] | None = None,
    *,
    force: bool = False,
    platform_name: str | None = None,
    python: str | os.PathLike[str] | None = None,
    script: str | os.PathLike[str] | None = None,
) -> dict[str, object]:
    platform = platform_name or os.name
    root = Path(directory).expanduser().resolve() if directory else default_directory(platform)
    paths = _paths(root, platform)
    current = status(root, platform_name=platform)
    if current["state"] in {"unmanaged", "drifted"} and not force:
        raise LauncherError(
            f"refusing to replace {current['state']} launcher at {root}: {current.get('detail')}"
        )

    source = Path(script).expanduser().resolve() if script else source_script()
    if not source.is_file():
        raise LauncherError(f"Valkama source entry point is missing: {source}")
    interpreter = Path(python).expanduser().resolve() if python else Path(sys.executable).resolve()
    if not interpreter.is_file():
        raise LauncherError(f"Python interpreter is missing: {interpreter}")

    shim = _shim_bytes(source)
    command, command_mode = _command_bytes(platform, interpreter)
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "platform": platform,
        "source_script": str(source),
        "python": str(interpreter),
        "files": {
            paths["command"].name: _sha256(command),
            paths["shim"].name: _sha256(shim),
        },
    }
    manifest_bytes = (
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")

    _atomic_write(paths["shim"], shim, stat.S_IREAD | stat.S_IWRITE)
    _atomic_write(paths["command"], command, command_mode)
    _atomic_write(paths["manifest"], manifest_bytes, stat.S_IREAD | stat.S_IWRITE)
    result = status(root, platform_name=platform)
    if result["state"] != "installed":
        raise LauncherError(f"installed launcher failed verification: {result.get('detail')}")
    return result


def uninstall(
    directory: str | os.PathLike[str] | None = None,
    *,
    force: bool = False,
    platform_name: str | None = None,
) -> dict[str, object]:
    platform = platform_name or os.name
    root = Path(directory).expanduser().resolve() if directory else default_directory(platform)
    paths = _paths(root, platform)
    current = status(root, platform_name=platform)
    if current["state"] == "missing":
        return current
    if current["state"] in {"unmanaged", "drifted"} and not force:
        raise LauncherError(
            f"refusing to remove {current['state']} launcher at {root}: {current.get('detail')}"
        )
    for name in ("command", "shim", "manifest"):
        with contextlib.suppress(FileNotFoundError):
            paths[name].unlink()
    with contextlib.suppress(OSError):
        root.rmdir()
    return status(root, platform_name=platform)
